### ISSUE TITLE
use angular 2 for susper.com

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#43]
This issue is  regarding the discussion done on #32 . where we have decided to use angular 2 for the frontend (along with typescript and angular-cli).
As using a framework like angular2 makes us easier to maintain, clean ,write tests and easier to extend functionalities.
**Prototype**:

- Initially we will use two main components(one for the initial search page and the other for search results page).Later these components may be divided into subcomponents or extend these components with some more subcomponents based on the increasing complexity of the project.

- As the application complexity increases we might start using ngrx redux architecture for the application.

- we will try mostly to follow the same logic of present susper . if we find some logic parts better than the present ones during development those implementations will be discussed and added on approval to the angular2 branch.

- Also regarding the CSS framework for now we can continue with bootstrap.(since angular-material is in alpha, we have to wait for some time to adopt it).
**Tasks:**

- [ ] Setup angular-cli project

- [ ] implementation search page component

- [ ] implementation of search results component

extra tasks can be suggested/added.

**Comment by nikhilrayaprolu** [comment]
@mariobehling regarding the timeline for this project ,
you could expect 

1. the basic susper functionality(the two pages and the search results on keyword enter) by 19th January
2. adding the filters and search tools by 21 January
by which the core part of the present susper will be completed.
the present extra features of the susper could be added like

- help button(question mark at the end of the search bar)

- default search engine modal toast at the bottom
later we could once add tests and any extra features expected to the project. for now I am creating individual issues for each of the above tasks to make tracking work easier.
I have worked integrating this with travis on my repo which is near completion.
